# Site settings
title: dario • Security • Privacy
description: Security is a business requirement. Protecting privacy is good business. Understand - Take Action.
author: dario
url: https://dario.pw
french_url: https://dario.site
baseurl: ''
blog_url: 'blog'
logo: "/img/chklst.png"
email: contact@dario.pw
twitter_username: darioS3C
telephone_number: +1-XXX-XXX-XXXX
copyright: dario • Security • Privacy
# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]
gems:
  - jekyll-sitemap
# Build settings
markdown: kramdown
