# Site settings
title: dario • Security • Privacy
description: Understand - Take Action. Security is a business requirement. Protecting privacy is good business.
author: dario
url: https://dario.pw
french_url: https://dario.site
baseurl: ''
blog_url: 'blog'
logo: "/img/chklst.png"
email: contact@dario.com
twitter_username: darioS3C
telephone_number: +1-514-572-0424
copyright:
# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]
gems:
  - jekyll-sitemap
# Build settings
markdown: kramdown
